In [ ]:
============EDA===============
1) pandas     : Dataframe or data applications
2) numpy      : Numerical python for math operations
3)matplotlib  : For plots graphs
4)Seaborn    : For plots graphs
5) Bokhe     : For plots
6) plotly    : For plots

=============Machine learning============
7) Scikit learn(Sklearn) : ML models
8) stats                 : statistical models

======================Data retrival from sql scrapping================
9) Sqlite            : connect with database
10) Beautiful soup   : scrap the data from website
11) websocket        : scrap

===================== Deep learning/ computer vision==============
12)Tensorflow         : Google
13) Keras             : DL models
14)OpenCV             : Image operations
15)Pillow(PIL)        : Image operations
16) Pytorch           : Facebook
17)Pretrained model   
   VGG16
   Mobilenet
   RESNET
   RCNN
   MASKRCNN
   FASTERCNN
   YOLO
=================== Natural language process===========
18) NLTK        : natural language process
19) Scipy       : 
20) word2vec    (How words will convert into vector) :
21)GloVE
22) Worldcloud

=============== Hugging face==================
23) Transformers    : BERT  

========================== GenAI Models=============
24) OpenAI+Microsoft : GPT Models
25) Google           : Gemini
26) Amazon           : Q
27) Meta Facebook    : Meta AI
28) Apple
LLAMA
GEMMA
Dalle-E
T5
ALL ARE HAVING DIFFERENT DIFFERENT PACKAGES
======================= LANGCHAIN ===================
29) LangChain Framework
====================== Deployments ===================
30) Flask
31) Streamlit
32) Django
===================== MLops======================
33) Mlflow
34) Kubeflow
35) Azure Ai services : azure packages
36) GCP : GCP packages

**Step-1**
**Create a Dataframe**

- we will create a dataframe using list
- we will create a dataframe using dictionary

In [1]:
import pandas as pd

In [3]:
d1=pd.DataFrame()
d1

Empty DataFrame
Columns: []
Index: []

In [4]:
type(d1)

pandas.core.frame.DataFrame

**Step-2**

**Provide the data**

In [5]:
names=['simu','tanu','moni']
pd.DataFrame(names)

0
0  simu
1  tanu
2  moni

In [6]:
names=['simu','tanu','moni']
age=[20,19,18]
data=zip(names,age)
pd.DataFrame(data)

0   1
0  simu  20
1  tanu  19
2  moni  18

In [7]:
names=['simu','tanu','moni']
age=[20,19,18]
city=['Pune','Chikhali','Aurangabad']
pd.DataFrame(zip(names,age,city))

0   1           2
0  simu  20        Pune
1  tanu  19    Chikhali
2  moni  18  Aurangabad

**Step-3**

**Provide the column names**

In [8]:
names=['simu','tanu','moni']
pd.DataFrame(names,columns=['Names'])

Names
0  simu
1  tanu
2  moni

In [9]:
names=['simu','tanu','moni']
age=[20,19,18]
pd.DataFrame(zip(names,age),columns=['Names','Age'])

Names  Age
0  simu   20
1  tanu   19
2  moni   18

In [10]:
names=['simu','tanu','moni']
age=[20,19,18]
city=['Pune','Chikhali','Aurangabad']
pd.DataFrame(zip(names,age,city),columns=['Names','Age','City'])

Names  Age        City
0  simu   20        Pune
1  tanu   19    Chikhali
2  moni   18  Aurangabad

In [11]:
names=['simu','tanu','moni']
age=[20,19,18]
city=['Pune','Chikhali','Aurangabad']
data=zip(names,age,city)
cols=['Names','Age','City']
pd.DataFrame(data,columns=cols)

Names  Age        City
0  simu   20        Pune
1  tanu   19    Chikhali
2  moni   18  Aurangabad

**Step-4**

**Providing index**

In [15]:
names=['simu','tanu','moni']
age=[20,19,18]
city=['Pune','Chikhali','Aurangabad']
data=zip(names,age,city)
ix=['A','B','C'] #3 rows we need 3 index
cols=['Names','Age','City'] # 3 columns, 3 values
pd.DataFrame(data,index=ix,columns=cols)

Names  Age        City
A  simu   20        Pune
B  tanu   19    Chikhali
C  moni   18  Aurangabad

In [14]:
names=['simu','tanu','moni']
age=[20,19,18]
city=['Pune','Chikhali','Aurangabad']
data=zip(names,age)
 #3 rows we need 3 index
cols=['Names','Age']
pd.DataFrame(data,index=city,columns=cols)

Names  Age
Pune        simu   20
Chikhali    tanu   19
Aurangabad  moni   18

- create a dataframe
- provide the data
- add the column
- provide the column name
- provide the index

**Step-5**

**Add a new column on existing data frame**

In [3]:
# create a data frame 
# Name age city
import pandas as pd
names=['simu','tanu','moni']
age=[20,19,18]
city=['Pune','Chikhali','Aurangabad']
cols=['Names','Age','City']
df=pd.DataFrame(zip(names,age,city),columns=cols)
df

Names  Age        City
0  simu   20        Pune
1  tanu   19    Chikhali
2  moni   18  Aurangabad

- If you want to add a new column
- First check how many rows are there
- For example in above dataframe we have 3 rows
- your new column also should have 3 rows
- suppose I want to create a new column: **salary**
- make a list with 3 values
- salary=[10000,20000,30000]
**syntax**: dataframe[column]=list of values
- df['salary']=salary

In [4]:
df['Salary']=[10000,20000,30000]

In [5]:
df

Names  Age        City  Salary
0  simu   20        Pune   10000
1  tanu   19    Chikhali   20000
2  moni   18  Aurangabad   30000

In [7]:
salary=[10000,20000,30000]
df['Salary']=salary
df

Names  Age        City  Salary
0  simu   20        Pune   10000
1  tanu   19    Chikhali   20000
2  moni   18  Aurangabad   30000

**use case-1**

- Create empty data frame first
- Create 3 list using list comprehension
- list1=a values from 1 to 10
- list2= square of 1 to 10
- list3= cube of 1 to 10
- Finally make a dataframe

In [12]:
import pandas as pd
df=pd.DataFrame()
df

Empty DataFrame
Columns: []
Index: []

In [13]:
l1=[i for i in range(1,10)]
l2=[i**2 for i in range(1,10)]
l3=[i**3 for i in range(1,10)]
df['x']=l1
df['y']=l2
df['z']=l3
df

x   y    z
0  1   1    1
1  2   4    8
2  3   9   27
3  4  16   64
4  5  25  125
5  6  36  216
6  7  49  343
7  8  64  512
8  9  81  729

**Step-6**

**Update the already existed column**

- Create a new column
  - creating a new list salary=[10000,20000,30000]
  - df['s']
  - creating a new column the column name is our choice
- update existing column are same way only
  - Here also we need a make a list of values=number of rows
  - while updating the existing column
  - we need to provide already existed column name only
  - df['z']=list of values

In [14]:
Z=[i**4 for i in range(1,10)]
df['z']=Z
df

x   y     z
0  1   1     1
1  2   4    16
2  3   9    81
3  4  16   256
4  5  25   625
5  6  36  1296
6  7  49  2401
7  8  64  4096
8  9  81  6561

In [21]:
# dataframe name : df1
# list of values variable name:Z
# which column we want to update : z
df2=pd.DataFrame()
Z=[i**4 for i in range(1,10)]
df2['z']=Z
df2

z
0     1
1    16
2    81
3   256
4   625
5  1296
6  2401
7  4096
8  6561

**Step-7**

**Drop the column**

In [15]:
# How to check the columns
df.columns

Index(['x', 'y', 'z'], dtype='object')

- If you want to drop a specific column
- we will use drop method
- we already know about diffrence between keywords and methods
- keywords will use directly
- methods will use with corresponding dataframe
- **Method name: drop**

df.drop()
- Column:which column you want to drop
- axis : Represents the specified value is a row or column
  - axis=0 means row
  - axis=1 means column
  - by default axis=0
- inplace:will provide overwrite the dataframe or not
  - inplace=True , This indicates overwrite the dataframe
  - inplace=False , this indicates the modified dataframe will be use when you provide new variable for the operation

In [26]:
df.drop('x')
# we are not providing axis
# it assuming the provided value is a row
# by default axis=0 ===== rows

KeyError: "['x'] not found in axis"

In [16]:
df.drop('x',axis=1)
# after this in a new cell type df1
# you will see original dataframe
# because we did not provide inplace
# If you want to use below output
# you need to assign a variable
# df_new=df1.drop('x',axis=1)

y     z
0   1     1
1   4    16
2   9    81
3  16   256
4  25   625
5  36  1296
6  49  2401
7  64  4096
8  81  6561

In [17]:
df.drop('x',axis=1,inplace=True)
df

y     z
0   1     1
1   4    16
2   9    81
3  16   256
4  25   625
5  36  1296
6  49  2401
7  64  4096
8  81  6561

**You need to create a new column**

**Drop the old column**

**Step-8**

**drop the row**
- drop the column and drop the rows both are similar only
- the only difference is axis
  - axis=0 represents rows
  - by default axis=0 available
  - which means if we provide any value,it will represent rows only

In [2]:
# DataFrame name: df1
import pandas as pd
df=pd.DataFrame()
l1=[i for i in range(1,10)]
l2=[i**2 for i in range(1,10)]
l3=[i**3 for i in range(1,10)]
df['x']=l1
df['y']=l2
df['z']=l3
df

x   y    z
0  1   1    1
1  2   4    8
2  3   9   27
3  4  16   64
4  5  25  125
5  6  36  216
6  7  49  343
7  8  64  512
8  9  81  729

In [4]:
df.drop(4)
# If we run this we will get error
# by default axis=0 which represents about rows
# But 'x' is a column
# If you want to drop row,the provide the row index

x   y    z
0  1   1    1
1  2   4    8
2  3   9   27
3  4  16   64
5  6  36  216
6  7  49  343
7  8  64  512
8  9  81  729

In [6]:
# Multiple rows
# Multiple columns keep always in a list
df.drop([4,8])

x   y    z
0  1   1    1
1  2   4    8
2  3   9   27
3  4  16   64
5  6  36  216
6  7  49  343
7  8  64  512

In [7]:
df

x   y    z
0  1   1    1
1  2   4    8
2  3   9   27
3  4  16   64
4  5  25  125
5  6  36  216
6  7  49  343
7  8  64  512
8  9  81  729

In [9]:
df.columns[[0,1]]

Index(['x', 'y'], dtype='object')

In [8]:
df.drop([0,1],axis=1)
# [0,1] rows
# axis=1 columns
# error

KeyError: '[0, 1] not found in axis'

**step-9**

**How to select the column**

In [13]:
df['x']
# Series type
# no column name display
# Whenever you see this type : Series type

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
Name: x, dtype: int64

In [16]:
df[['x']]
# Data Frame

x
0  1
1  2
2  3
3  4
4  5
5  6
6  7
7  8
8  9

In [14]:
type(df['x'])

pandas.core.series.Series

In [15]:
type(df[['x']])

pandas.core.frame.DataFrame

In [17]:
df.x

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
Name: x, dtype: int64

- df['x'] : Series type
- df[['x']] : DataFrame type
- df.x : Series type

In [18]:
cols=['x','y']
df[cols]

x   y
0  1   1
1  2   4
2  3   9
3  4  16
4  5  25
5  6  36
6  7  49
7  8  64
8  9  81

In [20]:
df['x'].values

array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64)

- All values comes in an array
- Array means it is a list of elements only represents using numpy package
- Generally elements present in 4 ways
  - list : Basic representation
  - Numpy array : Array with Numpy package
  - Tensors : Tensorflow package
  - Torch  : Pytorch package

In [21]:
list1=[1,2,3,4,5]
list1

[1, 2, 3, 4, 5]

In [22]:
import numpy as np
np.array(list1)

array([1, 2, 3, 4, 5])

In [ ]:
# tensor([1,2,3,4,5])

In [23]:
list1=[1,2,3,4]
list2=[10,20,30,40]
list1+list2

[1, 2, 3, 4, 10, 20, 30, 40]

In [24]:
l1=np.array(list1)
l2=np.array(list2)
l1+l2

array([11, 22, 33, 44])

In [ ]:
# 3 days every day one numpy
# A new package in the market : numpy
# You know python

In [27]:
df['x'].values
# imagine we worked on an ML problem
# we got some series of values
# with that series of values also we can create a dataframe

array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64)

In [26]:
df['X']=df['x'].values
df

x   y    z  X
0  1   1    1  1
1  2   4    8  2
2  3   9   27  3
3  4  16   64  4
4  5  25  125  5
5  6  36  216  6
6  7  49  343  7
7  8  64  512  8
8  9  81  729  9

**Step-10**

**How to save the Dataframe**
- DataFrames we can save in two formates
  - csv :comma seperated value
  - xlsx : excel format
- In order to save any data
  - where you want to save : directory name
  - what is the name of the file for storing
  - what is the extension
- we already seen in file handling session 

In [31]:
#Case-1:saving file at same location where this python file
# import os
# os.getcwd()
# No need to provide directory path
# Directly give only name of the file
# and extension

In [29]:
# DataFrame name = df
df.to_csv('Data1.csv')
df.to_excel('Data1.xlsx')

**Step-11**

**How to read a DataFrame**

In [30]:
import pandas as pd
pd.read_csv('Data1.csv')

Unnamed: 0  x   y    z  X
0           0  1   1    1  1
1           1  2   4    8  2
2           2  3   9   27  3
3           3  4  16   64  4
4           4  5  25  125  5
5           5  6  36  216  6
6           6  7  49  343  7
7           7  8  64  512  8
8           8  9  81  729  9

In [32]:
import os
os.getcwd()

'C:\\Users\\sohel\\Documents\\Nareshit\\EDA'

In [33]:
import pandas as pd
pd.read_excel('Data1.xlsx')

Unnamed: 0  x   y    z  X
0           0  1   1    1  1
1           1  2   4    8  2
2           2  3   9   27  3
3           3  4  16   64  4
4           4  5  25  125  5
5           5  6  36  216  6
6           6  7  49  343  7
7           7  8  64  512  8
8           8  9  81  729  9

**Step-12**

**How to avoid index column**
- while we save the dataframe
- automatically a new column will create
- that we need to avoid
- Permission denied means close the data file from laptop

In [37]:
# DataFrame name = df
# save the data with out index column
df.to_csv('Data1.csv',index=False)
df.to_excel('Data1.xlsx',index=False)

In [35]:
# read the data
import pandas as pd
pd.read_csv('Data1.csv')

x   y    z  X
0  1   1    1  1
1  2   4    8  2
2  3   9   27  3
3  4  16   64  4
4  5  25  125  5
5  6  36  216  6
6  7  49  343  7
7  8  64  512  8
8  9  81  729  9

In [36]:
import pandas as pd
pd.read_excel('Data1.xlsx')

x   y    z  X
0  1   1    1  1
1  2   4    8  2
2  3   9   27  3
3  4  16   64  4
4  5  25  125  5
5  6  36  216  6
6  7  49  343  7
7  8  64  512  8
8  9  81  729  9